config/routes.rb
Taskmanager::Application.routes.draw do
  scope :module => :web do
    root :to => 'welcome#index'

    resources :stories do
      resources :comments, :only => [:create]
    end

    resources :users
    resource :session, :only => [:new, :create, :destroy]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content

  validates :content, :presence => true, :length => { :maximum => 255 }
  belongs_to :story
  belongs_to :user
end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :content, :owner_id, :state_event

  belongs_to :requester, class_name: :User
  belongs_to :owner, class_name: :User

  has_many :comments

  validates :content, :presence => true, :length => { :maximum => 255 }
  validates :owner, :presence => true

  state_machine :initial => :new do
    event :starting do
      transition any => :started
    end

    event :finishing do
      transition :started => :finished
    end

    event :accepting do
      transition :finished => :accepted
    end

    event :rejecting do
      transition :finished => :rejected
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  validates_presence_of :password, on: :create
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, email: true

  has_many :stories_out, class_name: :Story, foreign_key: :requester_id, dependent: :destroy
  has_many :stories_in, class_name: :Story, foreign_key: :owner_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = t 'titles.session.new'
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = t 'flash.session.error'
      @title = t 'titles.session.new'
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def new
    @story = Story.new
    @title = t 'titles.story.new'
  end

  def show
    @story = Story.find(params[:id])
  end

  def create
    @story = current_user.stories_out.build(params[:story])
    if @story.save
      redirect_to @story, notice: t('flash.story.create')
    else
      flash[:warning] = t 'flash.story.error'
      render :new
    end
  end

  def update
    story = Story.find(params[:id])
    story.state_event = params[:state_event] if story

    if story.save
      flash[:info] = t "flash.story.state_#{story.state}"
    else
      flash[:error] = t 'flash.story.update_error'
    end

    redirect_to story
  end

  def destroy
    story = Story.find(params[:id])
    story.destroy
    redirect_to current_user, notice: t('flash.story.destroyed')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(21)
    @title = t 'titles.user.index'
  end

  def new
    @user = User.new
    @title = t 'titles.user.new'
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, notify: t('flash.user.welcome')
    else
      @title = t 'titles.user.new'
      render :new
    end
  end

  def edit
    @user = current_user
    @title = t 'titles.user.edit'
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: t('flash.user.updated')
    else
      @title = t 'titles.user.edit'
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    if current_user?(user)
      flash[:error] = t 'flash.user.error_destroy_self'
    else
      user.destroy
      flash[:success] = t 'flash.user.destroyed'
    end
    redirect_to users_path
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  include AuthHelper
  include FlashHelper
  include TitlesHelper

  helper_method :title, :sign_in, :sign_out, :signed_in?, :current_user, :current_user?
  
  private

  def title(part = nil)
    @parts ||= []
    unless part
      return nil if @parts.blank?
      return @parts.reverse.join(' - ')
    end
    @parts << part
  end
end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController
  def new
    title t_t :new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = f_t :error
      title t_t :new
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/web/stories/application_controller.rb
class Web::Stories::ApplicationController < Web::ApplicationController
  helper_method :current_story

  private
  
  def current_story
    @current_story ||= Story.find(params[:story_id])
  end
end

app/controllers/web/stories/comments_controller.rb
class Web::Stories::CommentsController < Web::Stories::ApplicationController
  def create
    @comment = current_story.comments.build(params[:comment])
    @comment.user = current_user

    if @comment.save
      flash[:success] = f_t :created
    else
      flash[:error] = f_t :error
    end

    redirect_to current_story
  end
end

app/controllers/web/stories_controller.rb
class Web::StoriesController < Web::ApplicationController
  def new
    @story = Story.new
    @title = t_t 'new'
  end

  def show
    @story = Story.find(params[:id])
    @title = @story.content
  end

  def create
    @story = current_user.stories_out.build(params[:story])
    if @story.save
      flash[:success] = f_t 'create'
      redirect_to @story
    else
      flash[:warning] = f_t 'error'
      render :new
    end
  end

  def update
    story = Story.find(params[:id])
    story.state_event = params[:state_event]

    if story.save
      flash[:success] = f_t "state_#{story.state}"
    else
      flash[:error] = f_t 'update_error'
    end

    redirect_to story
  end

  def destroy
    story = Story.find(params[:id])
    story.destroy
    flash[:success] = f_t :destroyed
    redirect_to current_user
  end
end

app/controllers/web/users_controller.rb
class Web::UsersController < Web::ApplicationController
  def index
    @users = User.page(params[:page])
    title t_t :index
  end

  def new
    @user = User.new
    title t_t :new
  end

  def show
    @user = User.find(params[:id])
    title @user.name
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = f_t :welcome
      redirect_to @user
    else
      title t_t :new
      render :new
    end
  end

  def edit
    @user = current_user
    title t_t :edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = f_t :updated
      redirect_to @user
    else
      title t_t :edit
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    if current_user?(user)
      flash[:error] = f_t :error_destroy_self
    else
      user.destroy
      flash[:success] = f_t :destroyed
    end
    redirect_to users_path
  end
end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def index
    title t_t :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def logo
		"Taskmanager"
	end

	def title
		base_title = "Taskmanager"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { :size => 96 })
		id = Digest::MD5.hexdigest(user.email)
		url = 'http://0.gravatar.com/avatar/' + id + '.jpg?s=' +
      options[:size].to_s + '&d=identicon'
		size = options[:size]
		options.delete :size
		options.each {|k,v| url += "&#{k}=#{v}" unless v.nil?}
		options[:width] = options[:height] = size
		options[:alt] = user.name
		image_tag url, options
	end
end

app/views/layouts/_footer.html.haml
%footer.footer
  %ul.nav.nav-pills
    %li= link_to I18n.t("titles.welcome.index"), root_path
    - if signed_in?
      %li= link_to I18n.t("titles.user.index"), users_path
    - else
      %li= link_to I18n.t("titles.user.new"), new_session_path

app/views/layouts/_navbar-top.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to logo, root_path, :class => "brand"
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .nav-collapse.collapse
        %ul.nav
          - if signed_in?
            %li= link_to t('titles.user.stories'), user_path(current_user)
            %li= link_to t('titles.user.index'), users_path
          - else
            %li= link_to t('titles.welcome.index'), root_path
            %li= link_to t('titles.user.new'), new_user_path
      .btn-group
        - if signed_in?
          = link_to t('titles.user.settings'), edit_user_path(current_user), :class => "btn btn-primary"
          = link_to t('titles.session.destroy'), session_path, :method => :delete, :class => "btn btn-primary"
        - else
          = link_to t('titles.session.new'), new_session_path, :class => "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= title
    = csrf_meta_tag
    /[if lt IE 9]
      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    = stylesheet_link_tag :application
    = javascript_include_tag :application
  %body
    = render 'layouts/navbar-top'
    #wrapper
      .container
        - flash.each do |key, value|
          %div{:class => "alert alert-#{key}"}
            %button.close{"data-dismiss" => "alert"} ×
            %span= value
        %section#global
          = yield
        = render 'layouts/footer'
        = debug(params) if Rails.env.development?

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  .alert.alert-error
    %p= I18n.t("simple_form.error_notification.default_message")
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/users/show.html.haml
.row
  .span4.well
    = render 'users/nav'
    = link_to t('titles.story.new'), new_story_path, :class => 'btn'
  .span7.well
    .row
      .span1.gravatar
        = gravatar_for @user, :size => 96
      .span5
        %h1= @user.name
    - unless @user.stories_in.empty?
      .content
        %ul.stories.unstyled
          = render @user.stories_in
        .clear

app/views/web/stories/_story.html.haml
%li{:class => story.state}
  %div
    %a{:href => user_path(story.owner)}
      = gravatar_for story.owner, :size => 64, :class => :gravatar
      %strong= story.owner.name
    %span
      \&nbsp;&rarr;&nbsp;#{link_to story.user.name, user_path(story.user)}
    %small
      = time_ago_in_words(story.created_at)
    %p= story.content
    = link_to I18n.t('titles.story.comments') + ' (' + story.comments.count.to_s + ')', |
      '#',                                                                         |
      :class => 'comments'                                                         |
    - if current_user?(story.user)
      .btn-group
        - if story.new?
          = link_to I18n.t("titles.story.accept"),         |
            story_path(story, :state_event => :accepting), |
            :method => :put,                               |
            :class => "btn btn-mini btn-success"           |
          -#
          = link_to I18n.t("titles.story.reject"),         |
            story_path(story, :state_event => :rejecting), |
            :method => :put,                               |
            :class => "btn btn-mini btn-danger"            |
        - elsif story.accepted?
          = link_to I18n.t("titles.story.start"),         |
            story_path(story, :state_event => :starting), |
            :method => :put,                              |
            :class => "btn btn-mini btn-primary"          |
        - elsif story.started?
          = link_to I18n.t("titles.story.finish"),         |
            story_path(story, :state_event => :finishing), |
            :method => :put,                               |
            :class => "btn btn-mini btn-info"              |
    - if current_user?(story.owner)
      .btn-group
        = link_to I18n.t("titles.story.delete"), story, |
          :method => :delete,                           |
          :confirm => I18n.t("messages.story.delete"),  |
          :class => "btn btn-mini btn-danger"           |
    - if story.rejected?
      .btn-group
        %span
          = I18n.t("titles.story.state_rejected")
    - elsif story.finished?
      .btn-group
        %span
          = I18n.t("titles.story.state_finished")
  %div.comments
    - unless story.comments.empty?
      %ul.unstyled
        = render story.comments
    = render 'comments/form', :story => story

app/views/web/stories/comments/_comment.html.haml
%li
  %div
    %a{:href => user_path(comment.user)}
      = gravatar_for comment.user, :size => 32, :class => :gravatar
      %strong= comment.user.name
    %small
      = time_ago_in_words(comment.created_at)
    %p= comment.content

app/views/web/stories/new.html.haml
.well
  .page-header
    %h1
      = t('titles.story.new')
  = simple_form_for(@story, url: stories_path, html: { class: 'form-horizontal' }) do |f|
    .row
      .span2
        %br/
      .span9
        = f.input :content, as: :text, input_html: { rows: "", cols: "" }
        = f.association :owner, include_blank: false
    .form-actions
      .span2
        %br/
      = f.button :submit, t('helpers.submit.story.create')

app/views/web/stories/show.html.haml
%h1
  = @story.content

app/views/web/users/_fields.html.haml
.span9
  = f.input :name
  = f.input :email
  = f.input :password
  = f.input :password_confirmation

app/views/web/users/_nav.html.haml
%ul.nav.nav-list
  %li
    \#{link_to t('titles.story.state_any'), user_path(@user)}
    %small
    - ['new', 'accepted', 'rejected', 'started', 'finished'].each do |state|
      %li
        \#{link_to t('titles.story.menu_' + state), user_path(@user, :state => state)}
        %small

app/views/web/users/_user.html.haml
%li
  - if current_user.admin? && ! current_user?(user)
    = link_to "×", user, :method => :delete,      |
      :class => "delete",                         |
      :confirm => I18n.t("messages.user.delete"), |
      :title => I18n.t("titles.user.delete")      |
  %a{:href => user_path(user)}
    %b
    = gravatar_for user, :size => 128
    %span= user.name

app/views/web/users/edit.html.haml
.well
  .page-header
    %h1= @title
  .row
    .span4
      %br/
  = simple_form_for(@user, :html => {:class => 'form-horizontal' }) do |f|
    = render 'shared/error_messages', :object => f.object
    .row
      .span2.gravatar
        %p
          %a{:href => "http://gravatar.com/emails", :target => "_blank"}
            = gravatar_for @user, :size => 100
            %span.nowrap= I18n.t("titles.user.gravatar_edit")
      = render 'fields', :f => f
    .form-actions
      .span2
        %br/
      = f.button :submit

app/views/web/users/index.html.haml
.well
  .page-header
    %h1= @title
  .row
    %ul.users.unstyled
      = render @users
  = paginate @users

app/views/web/users/new.html.haml
.well
  .page-header
    %h1= @title
  .row
    .span4
      %br/
  = simple_form_for(@user, :html => {:class => 'form-horizontal' }) do |f|
    = render 'shared/error_messages', :object => f.object
    .row
      .span2
        %br/
      = render 'fields', :f => f
    .form-actions
      .span2
        %br/
      = f.button :submit

app/views/web/users/show.html.haml
.row
  .span4.well
    = render 'nav'
    = link_to t('titles.story.new'), new_story_path, :class => 'btn'
  .span7.well
    .row
      .span1.gravatar
        = gravatar_for @user, :size => 96
      .span5
        %h1= @user.name
    - unless @user.stories_in.empty?
      .content
        %ul.stories.unstyled
          = render @user.stories_in
        .clear

app/views/web/welcome/index.html.haml
.hero-unit
  %h1 Управлять задачами просто
  %p
    Taskmanager ­— это простое приложение для управления задачами.
    Он позволяет создавать задачи, менять их статус, и добавлять комментарии к ним.
  %p
    = link_to t("titles.welcome.try"), new_session_path, :class => "btn btn-success btn-large"